### ISSUE TITLE
Please add wavpack support

### ISSUE THREAD

**Issue by agilov** [Intervention/mimesniffer#2]
Hello! Please add Wavpack support. Magick number is `7776706B` (wvpk) mime-type `audio/x-wavpack`.

Format description: https://en.wikipedia.org/wiki/WavPack

Test file: [test-wavpack.zip](https://github.com/Intervention/mimesniffer/files/9372646/test-wavpack.zip)

**Comment by olivervogel** [comment]
Please add a pull request.
